export const initialState = {
  user: 'admin',
  posts: {
    data: [
      {
        id: '1',
        title: 'Title #1',
        author: 'John Doe',
        email: 'john.doe@gmail.com',
        outline: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse molestie dapibus erat sit amet porta. Fusce velit lectus, fermentum sit amet maximus in, ultrices sit amet sem.',
        content: 'Pellentesque id urna euismod ex vulputate commodo. Praesent a sollicitudin massa. Nullam sit amet mi sit amet metus efficitur facilisis vitae non libero. Vivamus a nisi in elit cursus aliquet at et urna. Vestibulum non sem accumsan, commodo magna sagittis, scelerisque sem. Donec pellentesque vitae nunc tincidunt iaculis. Suspendisse sodales magna ac congue molestie. In hac habitasse platea dictumst. Donec ac odio id eros laoreet bibendum sagittis in lacus. Morbi porttitor ligula vel risus suscipit, mollis porta sapien tincidunt. Quisque malesuada ultricies justo at dictum. In hendrerit eros eros, nec tincidunt ante dapibus sit amet. Sed convallis rhoncus neque, ut imperdiet magna molestie a.',
        image: 'https://images.unsplash.com/photo-1552254332-c4ce6734d9f5?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80',
        phoneNr: '',
        price: '450$',
        localisation: '',
        publishDate: '20.09.2020',
        updateDate: '20.09.2020',
        state: 'published',
      },
      {
        id: '2',
        title: 'Title #2',
        author: 'John Doe',
        email: 'john.doe@gmail.com',
        outline: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse molestie dapibus erat sit amet porta. Fusce velit lectus, fermentum sit amet maximus in, ultrices sit amet sem.',
        content: 'Pellentesque id urna euismod ex vulputate commodo. Praesent a sollicitudin massa. Nullam sit amet mi sit amet metus efficitur facilisis vitae non libero. Vivamus a nisi in elit cursus aliquet at et urna. Vestibulum non sem accumsan, commodo magna sagittis, scelerisque sem. Donec pellentesque vitae nunc tincidunt iaculis. Suspendisse sodales magna ac congue molestie. In hac habitasse platea dictumst. Donec ac odio id eros laoreet bibendum sagittis in lacus. Morbi porttitor ligula vel risus suscipit, mollis porta sapien tincidunt. Quisque malesuada ultricies justo at dictum. In hendrerit eros eros, nec tincidunt ante dapibus sit amet. Sed convallis rhoncus neque, ut imperdiet magna molestie a.',
        image: 'https://images.unsplash.com/photo-1588511986632-592db3d6c81f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
        phoneNr: '',
        price: '650$',
        localisation: '',
        publishDate: '20.09.2020',
        updateDate: '20.09.2020',
        state: 'published',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
